name: 🚀 Deploy

# Trigger this workflow after the Security & Build workflow completes successfully
on:
  workflow_run:
    workflows: ["Security & Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Mainnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile --show-stack-traces

      - name: Deploy to Mainnet
        env:
          INFURA_SEPOLIA_ENDPOINT: ${{ secrets.INFURA_SEPOLIA_ENDPOINT }}
          ALCHEMY_MAINNET_ENDPOINT: ${{ secrets.ALCHEMY_MAINNET_ENDPOINT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npx hardhat run scripts/deploy.js --network mainnet
